### ISSUE TITLE
npm:Hono now supported on deno deploy

### ISSUE THREAD

**Issue by guy-borderless** [honojs/website#100]
I think we should now only recommend npm:Hono in the [getting started tutorial for deno](https://hono.dev/getting-started/deno)

**Comment by NicoPlyley** [comment]
Without full testing of all our packages, I would not change all the imports yet. And according to deno there's not 100% compatibility yet. I think updating the npm specifier documentation for now would be the best choice

**Comment by guy-borderless** [comment]
Is the Hono test suite runnable in a way that can help test this?

**Comment by NicoPlyley** [comment]
@guy-borderless I would have to look into it a little more. But I think it would have to be testing using deno deploy itself or go through documentation of deno deploy to see exactly what is not supported. It appears since everything, at least in hono I don't know about the 3rd party middleware repo, is made for deno so it seems it would work.
