### ISSUE TITLE
404 can't take me home

### ISSUE THREAD

**Issue by ryuapp** [honojs/website#68]
When I go to 404 page and try to go home, there is no home.
I can redirect locally but I can't on hono.dev.

ex)
https://hono.dev/test
![image](https://github.com/honojs/website/assets/114303361/19307871-72e8-41e3-949d-79aa40121740)

**Comment by yusukebe** [comment]
Hi @ryuapp !

Thank you for raising this issue.

I've addressed this issue through #71, where I added a custom NotFound component to link the home without using SPA transition. This issue only occurs in production (Cloudflare Pages), and since I couldn't identify the cause, this solution is merely a workaround.
